/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#006a6a',
        'primary-container': '#1be3e3',
        'primary-fixed': '#49f9f9',
        'primary-fixed-dim': '#00dddd',
        'on-primary': '#ffffff',
        'on-primary-container': '#006161',
        'on-primary-fixed': '#002020',
        'on-primary-fixed-variant': '#004f50',
        secondary: '#2f6767',
        'secondary-container': '#b4edec',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#366d6d',
        tertiary: '#7b5800',
        'tertiary-container': '#ffc344',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#715100',
        background: '#f3fbfa',
        surface: '#f3fbfa',
        'surface-dim': '#d4dcdb',
        'surface-bright': '#f3fbfa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#edf5f4',
        'surface-container': '#e8efef',
        'surface-container-high': '#e2eae9',
        'surface-container-highest': '#dce4e3',
        'on-surface': '#151d1d',
        'on-surface-variant': '#3b4949',
        'inverse-surface': '#2a3232',
        'inverse-on-surface': '#eaf2f1',
        outline: '#6b7a79',
        'outline-variant': '#bacac9',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
        'label-md': ['Be Vietnam Pro', 'sans-serif'],
        'label-sm': ['Be Vietnam Pro', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-xl': '64px',
        gutter: '24px',
        'container-max': '1280px',
      },
      borderRadius: {
        xl: '0.75rem',
        '2xl': '1rem',
        xxl: '1.5rem',
      },
    },
  },
  plugins: [],
};
