apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secretName | default (printf "%s-secrets" (include "gourmet-flow.fullname" .)) }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "gourmet-flow.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: "{{ .Values.secrets.jwtSecret }}"
  JWT_REFRESH_SECRET: "{{ .Values.secrets.jwtRefreshSecret }}"

  AUTH_DATABASE_URL: "{{ .Values.secrets.authDatabaseUrl }}"
  USER_DATABASE_URL: "{{ .Values.secrets.userDatabaseUrl }}"
  RESTAURANT_DATABASE_URL: "{{ .Values.secrets.restaurantDatabaseUrl }}"
  MENU_DATABASE_URL: "{{ .Values.secrets.menuDatabaseUrl }}"
  CART_DATABASE_URL: "{{ .Values.secrets.cartDatabaseUrl }}"
  ORDER_DATABASE_URL: "{{ .Values.secrets.orderDatabaseUrl }}"
  PAYMENT_DATABASE_URL: "{{ .Values.secrets.paymentDatabaseUrl }}"
  DELIVERY_DATABASE_URL: "{{ .Values.secrets.deliveryDatabaseUrl }}"
