export const ORDER_STATUS = Object.freeze({
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  RESTAURANT_CONFIRMED: 'RESTAURANT_CONFIRMED',
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
});

export const DELIVERY_STATUS = Object.freeze({
  WAITING_FOR_RESTAURANT: 'WAITING_FOR_RESTAURANT',
  DRIVER_ASSIGNED: 'DRIVER_ASSIGNED',
  DRIVER_AT_RESTAURANT: 'DRIVER_AT_RESTAURANT',
  ORDER_PICKED_UP: 'ORDER_PICKED_UP',
  ON_THE_WAY: 'ON_THE_WAY',
  ARRIVING: 'ARRIVING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
});

export const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  CANCELLED: 'CANCELLED',
});

export const USER_ROLES = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  ADMINISTRATOR: 'ADMINISTRATOR',
});
