apiVersion: v1
kind: Secret
metadata:
  name: gourmet-flow-secrets
  namespace: gourmet-flow
type: Opaque
stringData:
  JWT_SECRET: "change-me-in-production"
  JWT_REFRESH_SECRET: "change-me-in-production"

  AUTH_DATABASE_URL: "postgresql://neondb_owner:npg_RYj3wZq1xXhr@ep-raspy-glade-a74ngzf5-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require"
  USER_DATABASE_URL: "postgresql://neondb_owner:npg_RYj3wZq1xXhr@ep-raspy-glade-a74ngzf5-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require"
  RESTAURANT_DATABASE_URL: "postgresql://neondb_owner:npg_RYj3wZq1xXhr@ep-raspy-glade-a74ngzf5-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require"
  MENU_DATABASE_URL: "postgresql://neondb_owner:npg_RYj3wZq1xXhr@ep-raspy-glade-a74ngzf5-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require"
  CART_DATABASE_URL: "postgresql://neondb_owner:npg_RYj3wZq1xXhr@ep-raspy-glade-a74ngzf5-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require"
  ORDER_DATABASE_URL: "postgresql://neondb_owner:npg_RYj3wZq1xXhr@ep-raspy-glade-a74ngzf5-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require"
  PAYMENT_DATABASE_URL: "postgresql://neondb_owner:npg_RYj3wZq1xXhr@ep-raspy-glade-a74ngzf5-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require"
  DELIVERY_DATABASE_URL: "postgresql://neondb_owner:npg_RYj3wZq1xXhr@ep-raspy-glade-a74ngzf5-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require"
