const menuItems = new Map();

const seedData = [
  {
    id: 'm1',
    restaurantId: 'r1',
    name: 'Burrata Pugliese',
    description: 'Fresh Puglia burrata served with heirloom tomatoes, aged balsamic reduction, and organic basil oil.',
    price: 18.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAVk1Wb1wI5FSvx3Dihn_LiGcgaJYGrFvN14YPuBMCDuxIovV11i7_2j5bq3oVT04UTcZMlUSFalaXN6CsG0_P1WJYqDM0h3Qc4AnzJKJmOMAIZUXBIcXyOyHMPaWwZr-rv8mIaf13C4zZpQhenw3vw9ncBtpZxEs0JjLhrQnW9RoNHJWslU1p3ZFtOlGNu1vaRtOUF3yuuSoaNIoMjcbxK176nODK5EhSznyXDNZtiMnYV4IsztTnQnP2KqkZZrdpKmEJpAYCdQq8',
    category: 'Antipasti',
    calories: 420,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: true,
    addOns: [
      { name: 'Extra Burrata', price: 6.00 },
      { name: 'Prosciutto Wrap', price: 4.00 },
    ],
  },
  {
    id: 'm2',
    restaurantId: 'r1',
    name: 'Carpaccio di Manzo',
    description: 'Wafer-thin beef tenderloin, wild rocket, 24-month aged Parmigiano, and lemon-truffle vinaigrette.',
    price: 22.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHC36g6MwWUa9zEgzAl17PnzCm1Dw2IXdmfAUIcx1oXuDLpUTNfBJCFNflrL_dxoY9jjcNxdySuhg_5ehbeAYK2qf1ZV7z7ry1Ghzi-bP9s_-VLc8I5i5nbULoXodDqbRK27STwuxBvJxgk8COSRM69thHVlG3qA87TshhpMD5HdtTSbE4bjnhk64RpSFx2rH99cNNP_0Lg8yyyj3jzE7d2nrInuvjIJqv8OXjMzulc_sXGmQpV1yWkToaoY6eb7kSIZif4U66BAk',
    category: 'Antipasti',
    calories: 310,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: false,
    addOns: [{ name: 'Extra Parmigiano', price: 3.00 }],
  },
  {
    id: 'm3',
    restaurantId: 'r1',
    name: 'Calamari Fritti',
    description: 'Crisp local squid rings with house-made spicy pomodoro and charred Sicilian lemon.',
    price: 19.50,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDv8VRHAJuqAxosm5G1hRcXwE9HzmBsl25he1at2fg45OhxOfXCCFg-wsI4WklSUdUT2DCLVLlraISLa_hy45ddCeYW2IDdk_263Ad3yvDl2BvaHzJQHkUCYTvsgn3t2QduKGqaOPIFBNq_WZK9e_plNcGfLRQRaMJ9gkDtI7-iENq1xoPS6jFXY3R8EgYoYnr5Cposk3GBJ7Lyd9tbn9jYjYlYjIlnfP4djbIBUY1JB9cZqJJAyvOEZ3j9KhlwCCVfh9jD1jowBgk',
    category: 'Antipasti',
    calories: 540,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: false,
    addOns: [{ name: 'Extra Marinara', price: 2.00 }],
  },
  {
    id: 'm4',
    restaurantId: 'r1',
    name: 'Bruschetta Mista',
    description: 'Duo of roasted sourdough: classic tomato-basil and whipped ricotta with fig jam.',
    price: 14.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB37ikrHWfmAtryEwop9A0dhOntK5PrL7Ls9pjoBBj7RSdS7Uf73rXocYXfGvrSeApWKqd8POJwuQJH3tyFQyn6LFj0bfhRm7_Lo9hLFTz3rdVmSdF5Qh_v3DrAndjAQNC6LskTu85vuX4BYZK2VxLBm4Rl4HfHI1gEF5uABGY-JQnuCYchVqm-N3ln2wH8eDsqjS62Qy8YTj5cLEXAELJH15FZsDIt_Cx8rLA5I34I-zpLZ1XkyuaBWGvrP2s0t9HDm72pwXEWT4Q',
    category: 'Antipasti',
    calories: 380,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm5',
    restaurantId: 'r1',
    name: 'Truffle Risotto',
    description: 'Arborio risotto with wild mushrooms, black truffle shavings, and aged Parmigiano-Reggiano.',
    price: 24.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCnxLAGNxPUKfragocPZQHc79Q0NlosyANRJU47BRkOYgAG0czvbMVaeC-BbLM8fRCKCnr8FZQi1GddLcOwGirBkFmy170twrnNOsoPafb4ty6u-3n3XaieXktVrSmzoZAQbm6QtOcZ4kkN7UhFGYWYGucaG_jzZ4QWF26X_1F-uvUQXH9mM-Ojjf5sDqx8PwQ413PyA3ERZx6A3aFACK2bnuBfx0J8dimvtIbwnK8O9vu6V1At7eAA3NFusOgYmh4qthn2Nc-X_yk',
    category: 'Primi Piatti',
    calories: 680,
    dietaryTags: ['Vegetarian', 'Gluten Free'],
    isAvailable: true,
    isFeatured: true,
    addOns: [
      { name: 'Extra Parmesan', price: 3.00 },
      { name: 'Add Shrimp', price: 8.00 },
    ],
  },
  {
    id: 'm6',
    restaurantId: 'r1',
    name: 'Tagliatelle al Tartufo',
    description: 'Hand-rolled tagliatelle in a creamy black truffle sauce, finished with fresh chives and Pecorino Romano.',
    price: 28.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCnxLAGNxPUKfragocPZQHc79Q0NlosyANRJU47BRkOYgAG0czvbMVaeC-BbLM8fRCKCnr8FZQi1GddLcOwGirBkFmy170twrnNOsoPafb4ty6u-3n3XaieXktVrSmzoZAQbm6QtOcZ4kkN7UhFGYWYGucaG_jzZ4QWF26X_1F-uvUQXH9mM-Ojjf5sDqx8PwQ413PyA3ERZx6A3aFACK2bnuBfx0J8dimvtIbwnK8O9vu6V1At7eAA3NFusOgYmh4qthn2Nc-X_yk',
    category: 'Primi Piatti',
    calories: 720,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: true,
    addOns: [{ name: 'Extra Truffle', price: 6.00 }],
  },
  {
    id: 'm7',
    restaurantId: 'r1',
    name: 'Gold Leaf Ganache',
    description: 'Artisanal dark chocolate ganache tart with 24k gold leaf, raspberry coulis, and vanilla bean cream.',
    price: 12.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjgSA-wALs2Tv-cCjsfFfr3ci7hpQL5zguJVqiYpgLUWn6PLqb4dSPQCbQgJQjUZqRKjUXoRn4rxZHTnet04VeTwhYGLazlvWJU0VLe3PBPslSfTVkil8cpfUvGVMqyJA-TFPebNepJ65zMtNpju54Hhr1thrfSNFj2tl7MJC1TnRDoUZVJ-cXzHoiARa_m3Kfw2iFeVP1XMfEhUUlMNBb54_jmNA48vk3U58-ahXvSdWUwqKptMLSSBsg8cE_iahYT6RJTtX7xPw',
    category: 'Dolci',
    calories: 450,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: true,
    addOns: [{ name: 'Extra Gold Flakes', price: 5.00 }],
  },
  {
    id: 'm8',
    restaurantId: 'r1',
    name: 'Tiramisu Classico',
    description: 'Traditional Italian tiramisu with mascarpone, espresso-soaked ladyfingers, and Valrhona cocoa dusting.',
    price: 11.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjgSA-wALs2Tv-cCjsfFfr3ci7hpQL5zguJVqiYpgLUWn6PLqb4dSPQCbQgJQjUZqRKjUXoRn4rxZHTnet04VeTwhYGLazlvWJU0VLe3PBPslSfTVkil8cpfUvGVMqyJA-TFPebNepJ65zMtNpju54Hhr1thrfSNFj2tl7MJC1TnRDoUZVJ-cXzHoiARa_m3Kfw2iFeVP1XMfEhUUlMNBb54_jmNA48vk3U58-ahXvSdWUwqKptMLSSBsg8cE_iahYT6RJTtX7xPw',
    category: 'Dolci',
    calories: 520,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm9',
    restaurantId: 'r2',
    name: 'Margherita DOC',
    description: 'San Marzano tomato, fresh buffalo mozzarella, basil, and extra virgin olive oil on a perfectly charred Neapolitan crust.',
    price: 16.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUJivoEjAWR9hIfJre_s4tct0mkIQuIwOySSCMMnZeNFg5nOprSrVfXVn7zAT5IJ1wQi0vgTrwq6diZMcKIMxjdsQ_KWuf_pbHxcrZ_zKTC6tkIT3gEX8Hd5JjKJ6cDoYHRKYAjh2tzwdoZOHgMa0QhD8GYhXad_cwkgTTETDVcmNLpXaV53M_2Trz4kHIw5JOB9zVhjXgTL1z8cFee71aBrQdkQhJ_X3EIYefoAigqH7DDEEJIu9glYyDI4GJ4A1yR7jLIVoCsEo',
    category: 'Pizza',
    calories: 850,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: true,
    addOns: [
      { name: 'Prosciutto', price: 4.00 },
      { name: 'Arugula', price: 2.00 },
    ],
  },
  {
    id: 'm10',
    restaurantId: 'r2',
    name: 'Diavola Piccante',
    description: 'Spicy salami, Calabrian chili, smoked mozzarella, and San Marzano tomato sauce on a thin Roman base.',
    price: 18.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUJivoEjAWR9hIfJre_s4tct0mkIQuIwOySSCMMnZeNFg5nOprSrVfXVn7zAT5IJ1wQi0vgTrwq6diZMcKIMxjdsQ_KWuf_pbHxcrZ_zKTC6tkIT3gEX8Hd5JjKJ6cDoYHRKYAjh2tzwdoZOHgMa0QhD8GYhXad_cwkgTTETDVcmNLpXaV53M_2Trz4kHIw5JOB9zVhjXgTL1z8cFee71aBrQdkQhJ_X3EIYefoAigqH7DDEEJIu9glYyDI4GJ4A1yR7jLIVoCsEo',
    category: 'Pizza',
    calories: 920,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: false,
    addOns: [{ name: 'Extra Chili Oil', price: 1.50 }],
  },
  {
    id: 'm11',
    restaurantId: 'r2',
    name: 'Panna Cotta',
    description: 'Silky vanilla panna cotta with wild berry compote and crushed pistachio.',
    price: 9.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjgSA-wALs2Tv-cCjsfFfr3ci7hpQL5zguJVqiYpgLUWn6PLqb4dSPQCbQgJQjUZqRKjUXoRn4rxZHTnet04VeTwhYGLazlvWJU0VLe3PBPslSfTVkil8cpfUvGVMqyJA-TFPebNepJ65zMtNpju54Hhr1thrfSNFj2tl7MJC1TnRDoUZVJ-cXzHoiARa_m3Kfw2iFeVP1XMfEhUUlMNBb54_jmNA48vk3U58-ahXvSdWUwqKptMLSSBsg8cE_iahYT6RJTtX7xPw',
    category: 'Dolci',
    calories: 350,
    dietaryTags: ['Vegetarian', 'Gluten Free'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm12',
    restaurantId: 'r2',
    name: 'Italian Salad',
    description: 'Mixed greens, cherry tomatoes, cucumber, olives, and lemon vinaigrette.',
    price: 10.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJjCobKQwpFeucTSgLEtct0BPKCH4Jqck_bu9lwAL20YZDupXrPIuAQm-YbpgSAQ4JzywWIS4ks88iAj_bVy0oyEK4yotPbhlaxoezDr6ocQVPrT3CxN5YI6v8155zeiQAPLvd6NK7-kBKOITWzaIcN93GFXOBxaJiwd9r5HRPsTS9gWeeEjmu2ckvyV4M42dmW4Z2aanw4u6Le92CZptnKh6AL2KglmKgPOqA4db0pCU0kH-kNOIyoPpS4KwVydRH2jFdEIy6VNI',
    category: 'Contorni',
    calories: 180,
    dietaryTags: ['Vegetarian', 'Gluten Free'],
    isAvailable: true,
    isFeatured: false,
    addOns: [{ name: 'Add Grilled Chicken', price: 5.00 }],
  },
  {
    id: 'm13',
    restaurantId: 'r2',
    name: 'Garlic Bread',
    description: 'Crispy sourdough with roasted garlic butter, parsley, and a sprinkle of sea salt.',
    price: 7.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuClQIPF5499Ze_Uenho3DGjmbvTtztctkR_E5jCQ6Sx2bBryuQL-uzHn7eEwhwrv-NcJCE5RX5NDmRIrwWMU5DX6aV-foEeALYrXXsw7wM_02P1nf2nox27cqVnuCowxz3JYIbKYHlV3xvEp5_ChX-yA1KHrKbJpbdGHi1HPTFKVfPqekMpKtgoCsDgam4IJ5OYYQFRO_IRpsAnv2cWFzKbYVj90GroD0hYns-yJHogvAQyYl6UvAejF4YYmx9v17nnJmknwL_WwLs',
    category: 'Antipasti',
    calories: 320,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm14',
    restaurantId: 'r2',
    name: 'Four Cheese Pizza',
    description: 'Mozzarella, gorgonzola, fontina, and parmesan with a honey truffle drizzle.',
    price: 20.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUJivoEjAWR9hIfJre_s4tct0mkIQuIwOySSCMMnZeNFg5nOprSrVfXVn7zAT5IJ1wQi0vgTrwq6diZMcKIMxjdsQ_KWuf_pbHxcrZ_zKTC6tkIT3gEX8Hd5JjKJ6cDoYHRKYAjh2tzwdoZOHgMa0QhD8GYhXad_cwkgTTETDVcmNLpXaV53M_2Trz4kHIw5JOB9zVhjXgTL1z8cFee71aBrQdkQhJ_X3EIYefoAigqH7DDEEJIu9glYyDI4GJ4A1yR7jLIVoCsEo',
    category: 'Pizza',
    calories: 980,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm15',
    restaurantId: 'r2',
    name: 'Tiramisu',
    description: 'Classic layered Italian dessert with mascarpone cream and espresso-soaked ladyfingers.',
    price: 10.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjgSA-wALs2Tv-cCjsfFfr3ci7hpQL5zguJVqiYpgLUWn6PLqb4dSPQCbQgJQjUZqRKjUXoRn4rxZHTnet04VeTwhYGLazlvWJU0VLe3PBPslSfTVkil8cpfUvGVMqyJA-TFPebNepJ65zMtNpju54Hhr1thrfSNFj2tl7MJC1TnRDoUZVJ-cXzHoiARa_m3Kfw2iFeVP1XMfEhUUlMNBb54_jmNA48vk3U58-ahXvSdWUwqKptMLSSBsg8cE_iahYT6RJTtX7xPw',
    category: 'Dolci',
    calories: 480,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm16',
    restaurantId: 'r2',
    name: 'Focaccia',
    description: 'Rosemary and sea salt focaccia with extra virgin olive oil dip.',
    price: 8.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuClQIPF5499Ze_Uenho3DGjmbvTtztctkR_E5jCQ6Sx2bBryuQL-uzHn7eEwhwrv-NcJCE5RX5NDmRIrwWMU5DX6aV-foEeALYrXXsw7wM_02P1nf2nox27cqVnuCowxz3JYIbKYHlV3xvEp5_ChX-yA1KHrKbJpbdGHi1HPTFKVfPqekMpKtgoCsDgam4IJ5OYYQFRO_IRpsAnv2cWFzKbYVj90GroD0hYns-yJHogvAQyYl6UvAejF4YYmx9v17nnJmknwL_WwLs',
    category: 'Antipasti',
    calories: 280,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm17',
    restaurantId: 'r3',
    name: 'Classic Smash Burger',
    description: 'Double smash patty, American cheese, pickles, onion, and special sauce on a brioche bun.',
    price: 14.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCy5s2V6VYo8eNH7bu_ac8TtjHLZZBq4GI6-fC-dAf9WPug1FrYYPUIVH2HycJtP6kRMPoLMOI714apB6o-lFl712a3TtKIIz2rUKzEHxO-NfXVt95Is9umLwahJhmDUJGkv9QMyc9WyMnUOmxR-A6Iq85Z_TyFFpQA9gRibZcywUPMogqdgfqlQhzxAeynxA0qBUlA3p5dCvIY_G93CWzXP3KLJ5kq__UAKygSywwG1pRsxDATWVjBvI4THh2T4eJg8kM2FGV52OA',
    category: 'Burgers',
    calories: 780,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: true,
    addOns: [
      { name: 'Extra Patty', price: 5.00 },
      { name: 'Bacon', price: 3.00 },
    ],
  },
  {
    id: 'm18',
    restaurantId: 'r3',
    name: 'Truffle Burger',
    description: 'Wagyu patty, truffle aioli, caramelized onions, aged gruyère, and arugula on a pretzel bun.',
    price: 19.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCy5s2V6VYo8eNH7bu_ac8TtjHLZZBq4GI6-fC-dAf9WPug1FrYYPUIVH2HycJtP6kRMPoLMOI714apB6o-lFl712a3TtKIIz2rUKzEHxO-NfXVt95Is9umLwahJhmDUJGkv9QMyc9WyMnUOmxR-A6Iq85Z_TyFFpQA9gRibZcywUPMogqdgfqlQhzxAeynxA0qBUlA3p5dCvIY_G93CWzXP3KLJ5kq__UAKygSywwG1pRsxDATWVjBvI4THh2T4eJg8kM2FGV52OA',
    category: 'Burgers',
    calories: 920,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: true,
    addOns: [],
  },
  {
    id: 'm19',
    restaurantId: 'r3',
    name: 'Crispy Chicken Sandwich',
    description: 'Buttermilk-brined chicken, slaw, pickles, and house sauce on a toasted potato bun.',
    price: 13.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCy5s2V6VYo8eNH7bu_ac8TtjHLZZBq4GI6-fC-dAf9WPug1FrYYPUIVH2HycJtP6kRMPoLMOI714apB6o-lFl712a3TtKIIz2rUKzEHxO-NfXVt95Is9umLwahJhmDUJGkv9QMyc9WyMnUOmxR-A6Iq85Z_TyFFpQA9gRibZcywUPMogqdgfqlQhzxAeynxA0qBUlA3p5dCvIY_G93CWzXP3KLJ5kq__UAKygSywwG1pRsxDATWVjBvI4THh2T4eJg8kM2FGV52OA',
    category: 'Burgers',
    calories: 650,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: false,
    addOns: [{ name: 'Avocado', price: 2.50 }],
  },
  {
    id: 'm20',
    restaurantId: 'r3',
    name: 'Truffle Fries',
    description: 'Hand-cut fries with truffle oil, parmesan, and fresh herbs.',
    price: 9.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJjCobKQwpFeucTSgLEtct0BPKCH4Jqck_bu9lwAL20YZDupXrPIuAQm-YbpgSAQ4JzywWIS4ks88iAj_bVy0oyEK4yotPbhlaxoezDr6ocQVPrT3CxN5YI6v8155zeiQAPLvd6NK7-kBKOITWzaIcN93GFXOBxaJiwd9r5HRPsTS9gWeeEjmu2ckvyV4M42dmW4Z2aanw4u6Le92CZptnKh6AL2KglmKgPOqA4db0pCU0kH-kNOIyoPpS4KwVydRH2jFdEIy6VNI',
    category: 'Sides',
    calories: 420,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: true,
    addOns: [{ name: 'Extra Truffle', price: 2.00 }],
  },
  {
    id: 'm21',
    restaurantId: 'r3',
    name: 'Onion Rings',
    description: 'Beer-battered thick-cut onion rings with smoked paprika aioli.',
    price: 8.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJjCobKQwpFeucTSgLEtct0BPKCH4Jqck_bu9lwAL20YZDupXrPIuAQm-YbpgSAQ4JzywWIS4ks88iAj_bVy0oyEK4yotPbhlaxoezDr6ocQVPrT3CxN5YI6v8155zeiQAPLvd6NK7-kBKOITWzaIcN93GFXOBxaJiwd9r5HRPsTS9gWeeEjmu2ckvyV4M42dmW4Z2aanw4u6Le92CZptnKh6AL2KglmKgPOqA4db0pCU0kH-kNOIyoPpS4KwVydRH2jFdEIy6VNI',
    category: 'Sides',
    calories: 380,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm22',
    restaurantId: 'r3',
    name: 'Bacon Cheeseburger',
    description: 'Angus beef patty, smoked bacon, cheddar, lettuce, tomato, and thousand island dressing.',
    price: 16.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCy5s2V6VYo8eNH7bu_ac8TtjHLZZBq4GI6-fC-dAf9WPug1FrYYPUIVH2HycJtP6kRMPoLMOI714apB6o-lFl712a3TtKIIz2rUKzEHxO-NfXVt95Is9umLwahJhmDUJGkv9QMyc9WyMnUOmxR-A6Iq85Z_TyFFpQA9gRibZcywUPMogqdgfqlQhzxAeynxA0qBUlA3p5dCvIY_G93CWzXP3KLJ5kq__UAKygSywwG1pRsxDATWVjBvI4THh2T4eJg8kM2FGV52OA',
    category: 'Burgers',
    calories: 880,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm23',
    restaurantId: 'r3',
    name: 'Veggie Burger',
    description: 'House-made black bean and quinoa patty, avocado, sprouts, and chipotle mayo.',
    price: 13.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCy5s2V6VYo8eNH7bu_ac8TtjHLZZBq4GI6-fC-dAf9WPug1FrYYPUIVH2HycJtP6kRMPoLMOI714apB6o-lFl712a3TtKIIz2rUKzEHxO-NfXVt95Is9umLwahJhmDUJGkv9QMyc9WyMnUOmxR-A6Iq85Z_TyFFpQA9gRibZcywUPMogqdgfqlQhzxAeynxA0qBUlA3p5dCvIY_G93CWzXP3KLJ5kq__UAKygSywwG1pRsxDATWVjBvI4THh2T4eJg8kM2FGV52OA',
    category: 'Burgers',
    calories: 520,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm24',
    restaurantId: 'r3',
    name: 'Milkshake',
    description: 'Thick hand-spun vanilla, chocolate, or strawberry milkshake with whipped cream.',
    price: 7.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjgSA-wALs2Tv-cCjsfFfr3ci7hpQL5zguJVqiYpgLUWn6PLqb4dSPQCbQgJQjUZqRKjUXoRn4rxZHTnet04VeTwhYGLazlvWJU0VLe3PBPslSfTVkil8cpfUvGVMqyJA-TFPebNepJ65zMtNpju54Hhr1thrfSNFj2tl7MJC1TnRDoUZVJ-cXzHoiARa_m3Kfw2iFeVP1XMfEhUUlMNBb54_jmNA48vk3U58-ahXvSdWUwqKptMLSSBsg8cE_iahYT6RJTtX7xPw',
    category: 'Drinks',
    calories: 450,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [{ name: 'Add Shot', price: 1.50 }],
  },
  {
    id: 'm25',
    restaurantId: 'r4',
    name: 'Omakase Sashimi',
    description: "Chef's selection of 12 pieces of the freshest sashimi, featuring tuna, salmon, yellowtail, and seasonal specials.",
    price: 32.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA127feajPPpVlOdQELe4J5kDpB3QM-08DNPjS2F5aDdXbp2CsKcp0cSYQQqvjrIvVEQ_OpjH4Q8Qw0XNdV5wnCipCROUNXQEE22Y_RjKGSXRCOEZx6c2bwM83Q3Ex9gGrZ7JCVw-yi8g_YxtSg4n4i9P1dnS9UYvRP6EvSEIu5nouNnu6x2rN_sKTNKE73kVwVyv5zxjkZX5hH0yZAfBmW84El8QptrOcrAF65rav6juWGH7vEu61Zt_s17teCjmdsDYDQsQO7G9w',
    category: 'Sashimi',
    calories: 420,
    dietaryTags: ['Gluten Free', 'Healthy'],
    isAvailable: true,
    isFeatured: true,
    addOns: [{ name: 'Extra Wasabi', price: 1.00 }],
  },
  {
    id: 'm26',
    restaurantId: 'r4',
    name: 'Dragon Roll',
    description: 'Shrimp tempura, avocado, cucumber, and eel sauce topped with spicy tuna and tobiko.',
    price: 18.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA127feajPPpVlOdQELe4J5kDpB3QM-08DNPjS2F5aDdXbp2CsKcp0cSYQQqvjrIvVEQ_OpjH4Q8Qw0XNdV5wnCipCROUNXQEE22Y_RjKGSXRCOEZx6c2bwM83Q3Ex9gGrZ7JCVw-yi8g_YxtSg4n4i9P1dnS9UYvRP6EvSEIu5nouNnu6x2rN_sKTNKE73kVwVyv5zxjkZX5hH0yZAfBmW84El8QptrOcrAF65rav6juWGH7vEu61Zt_s17teCjmdsDYDQsQO7G9w',
    category: 'Rolls',
    calories: 520,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: true,
    addOns: [],
  },
  {
    id: 'm27',
    restaurantId: 'r4',
    name: 'Miso Soup',
    description: 'Traditional white miso with silken tofu, wakame, green onions, and dashi broth.',
    price: 6.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJjCobKQwpFeucTSgLEtct0BPKCH4Jqck_bu9lwAL20YZDupXrPIuAQm-YbpgSAQ4JzywWIS4ks88iAj_bVy0oyEK4yotPbhlaxoezDr6ocQVPrT3CxN5YI6v8155zeiQAPLvd6NK7-kBKOITWzaIcN93GFXOBxaJiwd9r5HRPsTS9gWeeEjmu2ckvyV4M42dmW4Z2aanw4u6Le92CZptnKh6AL2KglmKgPOqA4db0pCU0kH-kNOIyoPpS4KwVydRH2jFdEIy6VNI',
    category: 'Soups',
    calories: 120,
    dietaryTags: ['Vegetarian', 'Gluten Free', 'Healthy'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm28',
    restaurantId: 'r4',
    name: 'Rainbow Roll',
    description: 'California roll topped with assorted sashimi, avocado, and sesame.',
    price: 20.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA127feajPPpVlOdQELe4J5kDpB3QM-08DNPjS2F5aDdXbp2CsKcp0cSYQQqvjrIvVEQ_OpjH4Q8Qw0XNdV5wnCipCROUNXQEE22Y_RjKGSXRCOEZx6c2bwM83Q3Ex9gGrZ7JCVw-yi8g_YxtSg4n4i9P1dnS9UYvRP6EvSEIu5nouNnu6x2rN_sKTNKE73kVwVyv5zxjkZX5hH0yZAfBmW84El8QptrOcrAF65rav6juWGH7vEu61Zt_s17teCjmdsDYDQsQO7G9w',
    category: 'Rolls',
    calories: 480,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm29',
    restaurantId: 'r4',
    name: 'Salmon Teriyaki',
    description: 'Grilled Atlantic salmon fillet with house teriyaki glaze, sesame, and steamed jasmine rice.',
    price: 24.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA127feajPPpVlOdQELe4J5kDpB3QM-08DNPjS2F5aDdXbp2CsKcp0cSYQQqvjrIvVEQ_OpjH4Q8Qw0XNdV5wnCipCROUNXQEE22Y_RjKGSXRCOEZx6c2bwM83Q3Ex9gGrZ7JCVw-yi8g_YxtSg4n4i9P1dnS9UYvRP6EvSEIu5nouNnu6x2rN_sKTNKE73kVwVyv5zxjkZX5hH0yZAfBmW84El8QptrOcrAF65rav6juWGH7vEu61Zt_s17teCjmdsDYDQsQO7G9w',
    category: 'Main',
    calories: 650,
    dietaryTags: ['Healthy'],
    isAvailable: true,
    isFeatured: false,
    addOns: [{ name: 'Extra Teriyaki', price: 2.00 }],
  },
  {
    id: 'm30',
    restaurantId: 'r4',
    name: 'Edamame',
    description: 'Steamed edamame with sea salt and chili flakes.',
    price: 7.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJjCobKQwpFeucTSgLEtct0BPKCH4Jqck_bu9lwAL20YZDupXrPIuAQm-YbpgSAQ4JzywWIS4ks88iAj_bVy0oyEK4yotPbhlaxoezDr6ocQVPrT3CxN5YI6v8155zeiQAPLvd6NK7-kBKOITWzaIcN93GFXOBxaJiwd9r5HRPsTS9gWeeEjmu2ckvyV4M42dmW4Z2aanw4u6Le92CZptnKh6AL2KglmKgPOqA4db0pCU0kH-kNOIyoPpS4KwVydRH2jFdEIy6VNI',
    category: 'Appetizers',
    calories: 180,
    dietaryTags: ['Vegetarian', 'Gluten Free', 'Healthy'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm31',
    restaurantId: 'r4',
    name: 'Tempura Prawns',
    description: 'Crispy tempura-battered king prawns with matcha salt and sweet chili dip.',
    price: 16.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDv8VRHAJuqAxosm5G1hRcXwE9HzmBsl25he1at2fg45OhxOfXCCFg-wsI4WklSUdUT2DCLVLlraISLa_hy45ddCeYW2IDdk_263Ad3yvDl2BvaHzJQHkUCYTvsgn3t2QduKGqaOPIFBNq_WZK9e_plNcGfLRQRaMJ9gkDtI7-iENq1xoPS6jFXY3R8EgYoYnr5Cposk3GBJ7Lyd9tbn9jYjYlYjIlnfP4djbIBUY1JB9cZqJJAyvOEZ3j9KhlwCCVfh9jD1jowBgk',
    category: 'Appetizers',
    calories: 450,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm32',
    restaurantId: 'r4',
    name: 'Matcha Cheesecake',
    description: 'Creamy matcha-infused New York cheesecake with red bean swirl and black sesame crumble.',
    price: 11.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjgSA-wALs2Tv-cCjsfFfr3ci7hpQL5zguJVqiYpgLUWn6PLqb4dSPQCbQgJQjUZqRKjUXoRn4rxZHTnet04VeTwhYGLazlvWJU0VLe3PBPslSfTVkil8cpfUvGVMqyJA-TFPebNepJ65zMtNpju54Hhr1thrfSNFj2tl7MJC1TnRDoUZVJ-cXzHoiARa_m3Kfw2iFeVP1XMfEhUUlMNBb54_jmNA48vk3U58-ahXvSdWUwqKptMLSSBsg8cE_iahYT6RJTtX7xPw',
    category: 'Desserts',
    calories: 380,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm33',
    restaurantId: 'r5',
    name: 'Al Pastor Tacos',
    description: 'Three street-style tacos with marinated pork, grilled pineapple, onion, and fresh cilantro.',
    price: 12.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCPLgbJpqvyGpjyB1ObijNwvE4SlIXG2VszuLO5prLp46C19jJwU9Ky-8yLXmoiNhBC-ZoGGDmY9aELTjnzrBHj7WH5HmRjUiVx_ipHdz3gmh7qC2sWIm_DzEohYtLYPSUeI_MfQLuIZZG8ynHnwA4rQAiEDV8Dm-gkU-88NRLhGgk67r-IFgTk4z96h5wdQcYk6_3YBE1OX_Dl_yGbmLZkPiyFamM91sdgOept7mXKiRxmLj9B0jB145bKdGbm_96lvPUtMInjk-8',
    category: 'Tacos',
    calories: 520,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: true,
    addOns: [{ name: 'Extra Guacamole', price: 2.50 }],
  },
  {
    id: 'm34',
    restaurantId: 'r5',
    name: 'Carnitas Burrito',
    description: 'Large flour tortilla filled with slow-braised pork, Mexican rice, black beans, cheese, and crema.',
    price: 14.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCPLgbJpqvyGpjyB1ObijNwvE4SlIXG2VszuLO5prLp46C19jJwU9Ky-8yLXmoiNhBC-ZoGGDmY9aELTjnzrBHj7WH5HmRjUiVx_ipHdz3gmh7qC2sWIm_DzEohYtLYPSUeI_MfQLuIZZG8ynHnwA4rQAiEDV8Dm-gkU-88NRLhGgk67r-IFgTk4z96h5wdQcYk6_3YBE1OX_Dl_yGbmLZkPiyFamM91sdgOept7mXKiRxmLj9B0jB145bKdGbm_96lvPUtMInjk-8',
    category: 'Burritos',
    calories: 780,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm35',
    restaurantId: 'r5',
    name: 'Guacamole & Chips',
    description: 'Tableside-prepared guacamole with crispy house tortilla chips.',
    price: 9.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJjCobKQwpFeucTSgLEtct0BPKCH4Jqck_bu9lwAL20YZDupXrPIuAQm-YbpgSAQ4JzywWIS4ks88iAj_bVy0oyEK4yotPbhlaxoezDr6ocQVPrT3CxN5YI6v8155zeiQAPLvd6NK7-kBKOITWzaIcN93GFXOBxaJiwd9r5HRPsTS9gWeeEjmu2ckvyV4M42dmW4Z2aanw4u6Le92CZptnKh6AL2KglmKgPOqA4db0pCU0kH-kNOIyoPpS4KwVydRH2jFdEIy6VNI',
    category: 'Appetizers',
    calories: 320,
    dietaryTags: ['Vegetarian', 'Gluten Free'],
    isAvailable: true,
    isFeatured: false,
    addOns: [{ name: 'Extra Spicy', price: 0.50 }],
  },
  {
    id: 'm36',
    restaurantId: 'r5',
    name: 'Fish Tacos',
    description: 'Beer-battered cod, cabbage slaw, pico de gallo, and chipotle crema on corn tortillas.',
    price: 14.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCPLgbJpqvyGpjyB1ObijNwvE4SlIXG2VszuLO5prLp46C19jJwU9Ky-8yLXmoiNhBC-ZoGGDmY9aELTjnzrBHj7WH5HmRjUiVx_ipHdz3gmh7qC2sWIm_DzEohYtLYPSUeI_MfQLuIZZG8ynHnwA4rQAiEDV8Dm-gkU-88NRLhGgk67r-IFgTk4z96h5wdQcYk6_3YBE1OX_Dl_yGbmLZkPiyFamM91sdgOept7mXKiRxmLj9B0jB145bKdGbm_96lvPUtMInjk-8',
    category: 'Tacos',
    calories: 480,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm37',
    restaurantId: 'r5',
    name: 'Quesadilla',
    description: 'Flour tortilla with Oaxaca cheese, mushrooms, and roasted poblano peppers.',
    price: 10.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCPLgbJpqvyGpjyB1ObijNwvE4SlIXG2VszuLO5prLp46C19jJwU9Ky-8yLXmoiNhBC-ZoGGDmY9aELTjnzrBHj7WH5HmRjUiVx_ipHdz3gmh7qC2sWIm_DzEohYtLYPSUeI_MfQLuIZZG8ynHnwA4rQAiEDV8Dm-gkU-88NRLhGgk67r-IFgTk4z96h5wdQcYk6_3YBE1OX_Dl_yGbmLZkPiyFamM91sdgOept7mXKiRxmLj9B0jB145bKdGbm_96lvPUtMInjk-8',
    category: 'Appetizers',
    calories: 420,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [{ name: 'Add Chicken', price: 3.00 }],
  },
  {
    id: 'm38',
    restaurantId: 'r5',
    name: 'Elote',
    description: 'Grilled Mexican street corn with crema, cotija cheese, chili powder, and lime.',
    price: 7.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJjCobKQwpFeucTSgLEtct0BPKCH4Jqck_bu9lwAL20YZDupXrPIuAQm-YbpgSAQ4JzywWIS4ks88iAj_bVy0oyEK4yotPbhlaxoezDr6ocQVPrT3CxN5YI6v8155zeiQAPLvd6NK7-kBKOITWzaIcN93GFXOBxaJiwd9r5HRPsTS9gWeeEjmu2ckvyV4M42dmW4Z2aanw4u6Le92CZptnKh6AL2KglmKgPOqA4db0pCU0kH-kNOIyoPpS4KwVydRH2jFdEIy6VNI',
    category: 'Sides',
    calories: 280,
    dietaryTags: ['Vegetarian', 'Gluten Free'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm39',
    restaurantId: 'r5',
    name: 'Churros',
    description: 'Crispy cinnamon-sugar churros with warm chocolate dipping sauce.',
    price: 8.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjgSA-wALs2Tv-cCjsfFfr3ci7hpQL5zguJVqiYpgLUWn6PLqb4dSPQCbQgJQjUZqRKjUXoRn4rxZHTnet04VeTwhYGLazlvWJU0VLe3PBPslSfTVkil8cpfUvGVMqyJA-TFPebNepJ65zMtNpju54Hhr1thrfSNFj2tl7MJC1TnRDoUZVJ-cXzHoiARa_m3Kfw2iFeVP1XMfEhUUlMNBb54_jmNA48vk3U58-ahXvSdWUwqKptMLSSBsg8cE_iahYT6RJTtX7xPw',
    category: 'Desserts',
    calories: 390,
    dietaryTags: ['Vegetarian'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm40',
    restaurantId: 'r5',
    name: 'Horchata',
    description: 'Traditional Mexican rice drink with cinnamon and vanilla.',
    price: 5.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJjCobKQwpFeucTSgLEtct0BPKCH4Jqck_bu9lwAL20YZDupXrPIuAQm-YbpgSAQ4JzywWIS4ks88iAj_bVy0oyEK4yotPbhlaxoezDr6ocQVPrT3CxN5YI6v8155zeiQAPLvd6NK7-kBKOITWzaIcN93GFXOBxaJiwd9r5HRPsTS9gWeeEjmu2ckvyV4M42dmW4Z2aanw4u6Le92CZptnKh6AL2KglmKgPOqA4db0pCU0kH-kNOIyoPpS4KwVydRH2jFdEIy6VNI',
    category: 'Drinks',
    calories: 220,
    dietaryTags: ['Vegetarian', 'Gluten Free'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm41',
    restaurantId: 'r6',
    name: 'Coq au Vin',
    description: 'Classic braised chicken in Burgundy wine with pearl onions, mushrooms, and lardons.',
    price: 28.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuClQIPF5499Ze_Uenho3DGjmbvTtztctkR_E5jCQ6Sx2bBryuQL-uzHn7eEwhwrv-NcJCE5RX5NDmRIrwWMU5DX6aV-foEeALYrXXsw7wM_02P1nf2nox27cqVnuCowxz3JYIbKYHlV3xvEp5_ChX-yA1KHrKbJpbdGHi1HPTFKVfPqekMpKtgoCsDgam4IJ5OYYQFRO_IRpsAnv2cWFzKbYVj90GroD0hYns-yJHogvAQyYl6UvAejF4YYmx9v17nnJmknwL_WwLs',
    category: 'Plats Principaux',
    calories: 720,
    dietaryTags: ['Gluten Free'],
    isAvailable: true,
    isFeatured: true,
    addOns: [{ name: 'Extra Sauce', price: 3.00 }],
  },
  {
    id: 'm42',
    restaurantId: 'r6',
    name: 'French Onion Soup',
    description: 'Rich caramelized onion soup with gruyère crouton and melted Comté cheese.',
    price: 14.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJjCobKQwpFeucTSgLEtct0BPKCH4Jqck_bu9lwAL20YZDupXrPIuAQm-YbpgSAQ4JzywWIS4ks88iAj_bVy0oyEK4yotPbhlaxoezDr6ocQVPrT3CxN5YI6v8155zeiQAPLvd6NK7-kBKOITWzaIcN93GFXOBxaJiwd9r5HRPsTS9gWeeEjmu2ckvyV4M42dmW4Z2aanw4u6Le92CZptnKh6AL2KglmKgPOqA4db0pCU0kH-kNOIyoPpS4KwVydRH2jFdEIy6VNI',
    category: 'Entrées',
    calories: 380,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm43',
    restaurantId: 'r6',
    name: 'Steak Frites',
    description: "Pan-seared ribeye with maître d'hôtel butter and crispy pommes frites.",
    price: 32.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCy5s2V6VYo8eNH7bu_ac8TtjHLZZBq4GI6-fC-dAf9WPug1FrYYPUIVH2HycJtP6kRMPoLMOI714apB6o-lFl712a3TtKIIz2rUKzEHxO-NfXVt95Is9umLwahJhmDUJGkv9QMyc9WyMnUOmxR-A6Iq85Z_TyFFpQA9gRibZcywUPMogqdgfqlQhzxAeynxA0qBUlA3p5dCvIY_G93CWzXP3KLJ5kq__UAKygSywwG1pRsxDATWVjBvI4THh2T4eJg8kM2FGV52OA',
    category: 'Plats Principaux',
    calories: 850,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: true,
    addOns: [
      { name: 'Peppercorn Sauce', price: 4.00 },
      { name: 'Truffle Butter', price: 5.00 },
    ],
  },
  {
    id: 'm44',
    restaurantId: 'r6',
    name: 'Escargots de Bourgogne',
    description: 'Baked Burgundy snails with garlic-herb butter and crusty baguette.',
    price: 16.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuClQIPF5499Ze_Uenho3DGjmbvTtztctkR_E5jCQ6Sx2bBryuQL-uzHn7eEwhwrv-NcJCE5RX5NDmRIrwWMU5DX6aV-foEeALYrXXsw7wM_02P1nf2nox27cqVnuCowxz3JYIbKYHlV3xvEp5_ChX-yA1KHrKbJpbdGHi1HPTFKVfPqekMpKtgoCsDgam4IJ5OYYQFRO_IRpsAnv2cWFzKbYVj90GroD0hYns-yJHogvAQyYl6UvAejF4YYmx9v17nnJmknwL_WwLs',
    category: 'Entrées',
    calories: 280,
    dietaryTags: [],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm45',
    restaurantId: 'r6',
    name: 'Crème Brûlée',
    description: 'Classic Madagascar vanilla custard with caramelized sugar top and fresh berries.',
    price: 11.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjgSA-wALs2Tv-cCjsfFfr3ci7hpQL5zguJVqiYpgLUWn6PLqb4dSPQCbQgJQjUZqRKjUXoRn4rxZHTnet04VeTwhYGLazlvWJU0VLe3PBPslSfTVkil8cpfUvGVMqyJA-TFPebNepJ65zMtNpju54Hhr1thrfSNFj2tl7MJC1TnRDoUZVJ-cXzHoiARa_m3Kfw2iFeVP1XMfEhUUlMNBb54_jmNA48vk3U58-ahXvSdWUwqKptMLSSBsg8cE_iahYT6RJTtX7xPw',
    category: 'Desserts',
    calories: 340,
    dietaryTags: ['Vegetarian', 'Gluten Free'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm46',
    restaurantId: 'r6',
    name: 'Salade Niçoise',
    description: 'Seared tuna, haricots verts, olives, hard-boiled egg, and anchovy vinaigrette.',
    price: 18.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJjCobKQwpFeucTSgLEtct0BPKCH4Jqck_bu9lwAL20YZDupXrPIuAQm-YbpgSAQ4JzywWIS4ks88iAj_bVy0oyEK4yotPbhlaxoezDr6ocQVPrT3CxN5YI6v8155zeiQAPLvd6NK7-kBKOITWzaIcN93GFXOBxaJiwd9r5HRPsTS9gWeeEjmu2ckvyV4M42dmW4Z2aanw4u6Le92CZptnKh6AL2KglmKgPOqA4db0pCU0kH-kNOIyoPpS4KwVydRH2jFdEIy6VNI',
    category: 'Entrées',
    calories: 420,
    dietaryTags: ['Gluten Free', 'Healthy'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm47',
    restaurantId: 'r6',
    name: 'Boeuf Bourguignon',
    description: 'Slow-braised beef in Burgundy wine with root vegetables and fresh thyme.',
    price: 26.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuClQIPF5499Ze_Uenho3DGjmbvTtztctkR_E5jCQ6Sx2bBryuQL-uzHn7eEwhwrv-NcJCE5RX5NDmRIrwWMU5DX6aV-foEeALYrXXsw7wM_02P1nf2nox27cqVnuCowxz3JYIbKYHlV3xvEp5_ChX-yA1KHrKbJpbdGHi1HPTFKVfPqekMpKtgoCsDgam4IJ5OYYQFRO_IRpsAnv2cWFzKbYVj90GroD0hYns-yJHogvAQyYl6UvAejF4YYmx9v17nnJmknwL_WwLs',
    category: 'Plats Principaux',
    calories: 680,
    dietaryTags: ['Gluten Free'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
  {
    id: 'm48',
    restaurantId: 'r6',
    name: 'Chocolate Mousse',
    description: 'Dark Valrhona chocolate mousse with whipped crème fraîche and cocoa nibs.',
    price: 12.00,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjgSA-wALs2Tv-cCjsfFfr3ci7hpQL5zguJVqiYpgLUWn6PLqb4dSPQCbQgJQjUZqRKjUXoRn4rxZHTnet04VeTwhYGLazlvWJU0VLe3PBPslSfTVkil8cpfUvGVMqyJA-TFPebNepJ65zMtNpju54Hhr1thrfSNFj2tl7MJC1TnRDoUZVJ-cXzHoiARa_m3Kfw2iFeVP1XMfEhUUlMNBb54_jmNA48vk3U58-ahXvSdWUwqKptMLSSBsg8cE_iahYT6RJTtX7xPw',
    category: 'Desserts',
    calories: 480,
    dietaryTags: ['Vegetarian', 'Gluten Free'],
    isAvailable: true,
    isFeatured: false,
    addOns: [],
  },
];

for (const item of seedData) {
  menuItems.set(item.id, item);
}

export function getMenuByRestaurant(restaurantId) {
  return Array.from(menuItems.values()).filter((item) => item.restaurantId === restaurantId);
}

export function getMenuByRestaurantGrouped(restaurantId) {
  const items = getMenuByRestaurant(restaurantId);
  const grouped = {};
  for (const item of items) {
    if (!grouped[item.category]) {
      grouped[item.category] = [];
    }
    grouped[item.category].push(item);
  }
  return grouped;
}

export function getMenuItemById(itemId) {
  return menuItems.get(itemId) || null;
}

export function getFeaturedItems() {
  return Array.from(menuItems.values()).filter((item) => item.isFeatured);
}

export function getAllCategories() {
  const all = new Set();
  for (const item of menuItems.values()) {
    all.add(item.category);
  }
  return Array.from(all).sort();
}
